FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    clang \
    clang-tidy \
    clang-format \
    cmake \
    make \
    libgtest-dev \
    zip \
    ca-certificates \
    && cd /usr/src/gtest && cmake . && make -j$(nproc) && cp lib/*.a /usr/lib && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /workspace
